# AmigaOS 3.x / OpenGPU SDK cross toolchain.
# Canonical revival target: 68040 + FPU, libnix, GCC 16.
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR m68k)

if(NOT DEFINED AMIGA_STOVE)
  if(DEFINED ENV{AMIGA_STOVE})
    set(AMIGA_STOVE "$ENV{AMIGA_STOVE}")
  else()
    set(AMIGA_STOVE "$ENV{HOME}/AmigaChrome/stoves/os32-gcc16")
  endif()
endif()

set(AMIGA_PREFIX "${AMIGA_STOVE}/prefix")
set(AMIGA_SYSROOT "${AMIGA_PREFIX}/m68k-amigaos")

set(CMAKE_C_COMPILER   "${AMIGA_PREFIX}/bin/m68k-amigaos-gcc")
set(CMAKE_CXX_COMPILER "${AMIGA_PREFIX}/bin/m68k-amigaos-g++")
set(CMAKE_AR           "${AMIGA_PREFIX}/bin/m68k-amigaos-ar" CACHE FILEPATH "")
set(CMAKE_RANLIB       "${AMIGA_PREFIX}/bin/m68k-amigaos-ranlib" CACHE FILEPATH "")
set(CMAKE_STRIP        "${AMIGA_PREFIX}/bin/m68k-amigaos-strip" CACHE FILEPATH "")

set(AMIGA_CPU_FLAGS "-m68040 -m68881" CACHE STRING "Amiga CPU/FPU flags")
set(AMIGA_RUNTIME "-noixemul" CACHE STRING "Amiga C runtime")
# Kept as defence-in-depth even after compiler fixes; not relied upon for correctness.
set(AMIGA_GCC16_WORKAROUND "-fno-tree-loop-distribute-patterns" CACHE STRING "Conservative GCC16 build flag")
set(AMIGA_THREAD_FLAGS "-pthread" CACHE STRING "Amiga pthread personality")

set(CMAKE_C_FLAGS_INIT
    "${AMIGA_RUNTIME} ${AMIGA_CPU_FLAGS} ${AMIGA_GCC16_WORKAROUND} ${AMIGA_THREAD_FLAGS}")
set(CMAKE_CXX_FLAGS_INIT
    "${AMIGA_RUNTIME} ${AMIGA_CPU_FLAGS} ${AMIGA_GCC16_WORKAROUND} ${AMIGA_THREAD_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS_INIT
    "${AMIGA_RUNTIME} ${AMIGA_CPU_FLAGS} ${AMIGA_THREAD_FLAGS}")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_PREFIX_PATH "${AMIGA_SYSROOT}" CACHE STRING "")
set(CMAKE_FIND_ROOT_PATH "${AMIGA_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_THREAD_LIBS_INIT "-lpthread")
set(THREADS_PREFER_PTHREAD_FLAG ON)
